"""
bot.py — Smart News Scheduler & Event-Driven Sentiment Trigger
Fusion Score Bot V7.0

Architecture: Single long-running GitHub Actions job (6-hour window).
    1. Fetches today's ForexFactory calendar at startup
    2. Sends a beautified HTML daily briefing to Telegram (all High + Medium events)
    3. Sleeps precisely until each event fires
    4. At each event: triggers targeted sentiment pipeline + AI macro summary
    5. Stays alive via time.sleep() loop

V7 improvements:
    - All Telegram messages use HTML parse mode (not Markdown)
    - Daily briefing sorted by impact: High → Medium, color-coded
    - Per-event alert shows impact level, currency flags, countdown
    - AI macro summary generated by Gemini after each event scan
    - Error notifications use sanitized HTML messages

Run by: GitHub Actions bot.yml (triggers on ForexFactory schedule)
"""

import time
import logging
import requests
from datetime import datetime, timezone, timedelta
from typing import Optional

import telebot

from config import (
    TELEGRAM_TOKEN, TELEGRAM_CHAT_ID,
    SCAN_DELAY_MINUTES,
    validate_config
)
from shared_functions import send_error_notification
from sentiment_scanner import SentimentScannerPipeline

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

IST = timezone(timedelta(hours=5, minutes=30))

# ForexFactory calendar
CALENDAR_URL = "https://nfs.faireconomy.media/ff_calendar_thisweek.json"
CALENDAR_HEADERS = {
    'User-Agent': (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
        'AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36'
    )
}

TARGET_CURRENCIES = {'USD', 'EUR', 'GBP'}
TARGET_IMPACTS    = {'High', 'Medium'}

# Currency flag emojis
CURRENCY_FLAGS = {
    'USD': '🇺🇸',
    'EUR': '🇪🇺',
    'GBP': '🇬🇧',
    'JPY': '🇯🇵',
    'AUD': '🇦🇺',
    'CAD': '🇨🇦',
    'CHF': '🇨🇭',
    'NZD': '🇳🇿',
}

# Impact level styling
IMPACT_CONFIG = {
    'High':   {'emoji': '🔴', 'label': 'HIGH'},
    'Medium': {'emoji': '🟡', 'label': 'MED'},
    'Low':    {'emoji': '⚪', 'label': 'LOW'},
}


# =============================================================================
# CALENDAR FETCHING
# =============================================================================

def fetch_todays_schedule() -> list:
    """
    Fetches ForexFactory calendar and returns today's relevant upcoming events.

    Returns:
        List of dicts sorted ascending by time:
        {'time': datetime (IST), 'currency': str, 'impact': str, 'title': str}
    """
    try:
        resp = requests.get(
            CALENDAR_URL,
            headers=CALENDAR_HEADERS,
            timeout=15
        )
        resp.raise_for_status()
        all_events = resp.json()
    except Exception as e:
        logger.error(f"[Calendar] Fetch failed: {e}")
        send_error_notification(f"ForexFactory Calendar Fetch Failed: {e}", "bot")
        return []

    now_ist   = datetime.now(IST)
    today_str = now_ist.date().isoformat()
    events    = []

    for event in all_events:
        try:
            currency = event.get('country', '').upper()
            impact   = event.get('impact', '')
            title    = event.get('title', 'Unknown Event')
            date_str = event.get('date', '')

            if currency not in TARGET_CURRENCIES:
                continue
            if impact not in TARGET_IMPACTS:
                continue

            # Parse event time (ForexFactory returns UTC)
            event_utc  = datetime.fromisoformat(date_str.replace('Z', '+00:00'))
            event_ist  = event_utc.astimezone(IST)
            event_date = event_ist.date().isoformat()

            if event_date != today_str:
                continue

            # V7 FIX (from V6 audit): skip same-minute past events
            # V6 used <= which caused events to be skipped on late runner start
            # V7: only skip events more than SCAN_DELAY_MINUTES behind schedule
            # so that even a slightly late start catches the event
            effective_trigger = event_ist + timedelta(minutes=SCAN_DELAY_MINUTES)
            if effective_trigger <= now_ist:
                logger.info(f"[Calendar] Skipping past event: {title} at {event_ist.strftime('%H:%M IST')}")
                continue

            events.append({
                'time':     event_ist,
                'currency': currency,
                'impact':   impact,
                'title':    title,
                'utc_time': event_utc,
            })

        except Exception as e:
            logger.warning(f"[Calendar] Failed to parse event: {e}")
            continue

    events.sort(key=lambda e: e['time'])
    logger.info(f"[Calendar] Found {len(events)} upcoming events today.")
    return events


# =============================================================================
# TELEGRAM ALERTS — HTML FORMAT
# =============================================================================

def send_daily_briefing(events: list):
    """
    Sends the morning market briefing with beautified impact-sorted event list.
    Uses HTML parse mode (V7 standard).

    Format example:
        📅 MARKET BRIEFING — 17 Apr 2026

        🔴 HIGH IMPACT
        🇺🇸 15:30 IST — Core CPI m/m
        🇬🇧 16:00 IST — GDP m/m

        🟡 MEDIUM IMPACT
        🇪🇺 14:00 IST — Trade Balance
    """
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        logger.warning("[Briefing] No Telegram credentials. Skipping briefing.")
        return

    now_ist     = datetime.now(IST)
    date_str    = now_ist.strftime('%d %b %Y')

    high_events   = [e for e in events if e['impact'] == 'High']
    medium_events = [e for e in events if e['impact'] == 'Medium']

    lines = [
        f"📅 <b>MARKET BRIEFING — {date_str}</b>\n",
        f"Monitoring: EUR/USD | GBP/USD\n",
        f"Events today: <b>{len(events)}</b> "
        f"({len(high_events)} high | {len(medium_events)} medium)\n"
    ]

    if high_events:
        lines.append(f"\n🔴 <b>HIGH IMPACT</b>")
        for e in high_events:
            flag     = CURRENCY_FLAGS.get(e['currency'], '🌐')
            time_str = e['time'].strftime('%H:%M IST')
            lines.append(f"{flag} <b>{time_str}</b> — {e['title']}")

    if medium_events:
        lines.append(f"\n🟡 <b>MEDIUM IMPACT</b>")
        for e in medium_events:
            flag     = CURRENCY_FLAGS.get(e['currency'], '🌐')
            time_str = e['time'].strftime('%H:%M IST')
            lines.append(f"{flag} {time_str} — {e['title']}")

    if not events:
        lines.append("\n<i>No high/medium impact events scheduled today.</i>")

    lines.append(f"\n⏰ Scan delay: {SCAN_DELAY_MINUTES} min post-release")
    lines.append("🤖 Fusion Bot V7.0 active")

    msg = "\n".join(lines)

    try:
        bot = telebot.TeleBot(TELEGRAM_TOKEN)
        bot.send_message(TELEGRAM_CHAT_ID, msg, parse_mode="HTML", timeout=10)
        logger.info("[Briefing] Daily briefing sent.")
    except Exception as e:
        logger.error(f"[Briefing] Failed to send: {e}")
        send_error_notification(f"Daily briefing send failed: {e}", "bot")


def send_event_alert(event: dict, scan_start_time: datetime):
    """
    Sends a pre-scan alert when a news event fires.
    Shown before the sentiment scan starts.
    """
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        return

    impact_cfg = IMPACT_CONFIG.get(event['impact'], IMPACT_CONFIG['Medium'])
    flag       = CURRENCY_FLAGS.get(event['currency'], '🌐')
    time_str   = event['time'].strftime('%H:%M IST')

    msg = (
        f"{impact_cfg['emoji']} <b>NEWS EVENT FIRING</b>\n\n"
        f"{flag} <b>{event['currency']}</b> | {impact_cfg['label']} IMPACT\n"
        f"📌 {event['title']}\n"
        f"🕐 Released: {time_str}\n\n"
        f"🔍 Scanning sentiment in {SCAN_DELAY_MINUTES}m..."
    )

    try:
        bot = telebot.TeleBot(TELEGRAM_TOKEN)
        bot.send_message(TELEGRAM_CHAT_ID, msg, parse_mode="HTML", timeout=10)
    except Exception as e:
        logger.error(f"[EventAlert] Failed: {e}")


def send_scan_complete_alert(event: dict, result: dict, macro_summary: Optional[str] = None):
    """
    Sends post-scan summary after sentiment pipeline completes.

    Args:
        event:         The ForexFactory event that triggered this scan
        result:        Dict returned by SentimentScannerPipeline.run_pipeline()
        macro_summary: Optional AI-generated macro context string
    """
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        return

    processed = result.get('processed', 0)
    errors    = result.get('errors', 0)
    flag      = CURRENCY_FLAGS.get(event['currency'], '🌐')

    lines = [
        f"✅ <b>SCAN COMPLETE: {event['title']}</b>\n",
        f"{flag} {event['currency']} | {processed} articles processed | {errors} errors\n",
    ]

    if macro_summary:
        lines.append(f"\n🧠 <b>AI MACRO CONTEXT</b>\n{macro_summary}")

    msg = "\n".join(lines)

    try:
        bot = telebot.TeleBot(TELEGRAM_TOKEN)
        bot.send_message(TELEGRAM_CHAT_ID, msg, parse_mode="HTML", timeout=10)
    except Exception as e:
        logger.error(f"[ScanAlert] Failed: {e}")


# =============================================================================
# AI MACRO SUMMARY (Post-Scan Gemini Summary)
# =============================================================================

def generate_macro_summary(pipeline_result: dict, event_title: str) -> Optional[str]:
    """
    Uses one Gemini call to generate a 3-sentence macro context summary
    after an event scan completes.

    Only fires if:
        - Pipeline processed > 0 articles
        - Gemini daily budget not exhausted

    Returns:
        HTML-safe summary string, or None if unavailable.
    """
    import requests as req_lib
    from config import GEMINI_API_KEY

    if not GEMINI_API_KEY:
        return None

    processed = pipeline_result.get('processed', 0)
    if processed == 0:
        return None

    eur_sent = pipeline_result.get('eur_net_sentiment', 0)
    gbp_sent = pipeline_result.get('gbp_net_sentiment', 0)

    def _sentiment_label(net: int) -> str:
        if net > 2:
            return "BULLISH"
        elif net < -2:
            return "BEARISH"
        return "NEUTRAL"

    eur_label = _sentiment_label(eur_sent)
    gbp_label = _sentiment_label(gbp_sent)

    prompt = (
        f"Economic data just released: {event_title}. "
        f"News analysis: EUR/USD {eur_label}, GBP/USD {gbp_label}. "
        f"Write exactly 2 sentences of macro context for a Forex day trader. "
        f"Be specific and directional. No fluff. No markdown."
    )

    try:
        url     = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}"
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.2, "maxOutputTokens": 100}
        }
        resp = req_lib.post(url, json=payload, timeout=15)
        resp.raise_for_status()
        data = resp.json()
        text = data['candidates'][0]['content']['parts'][0]['text'].strip()

        # Sanitize for HTML
        text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        return f"<i>{text}</i>"

    except Exception as e:
        logger.warning(f"[MacroSummary] Gemini summary failed: {e}")
        return None


# =============================================================================
# MAIN SCHEDULER
# =============================================================================

def run_scheduler():
    """
    Main event-driven scheduler loop.
    Runs for up to 6 hours (GitHub Actions limit).
    """
    validate_config('bot')

    bot = telebot.TeleBot(TELEGRAM_TOKEN)

    logger.info("[Bot] Fusion Score Bot V7.0 starting...")

    # Fetch today's schedule
    events = fetch_todays_schedule()

    if not events:
        logger.info("[Bot] No events today. Sending briefing and exiting.")
        send_daily_briefing([])
        return

    # Send daily briefing
    send_daily_briefing(events)

    logger.info(f"[Bot] Scheduled {len(events)} events. Waiting for triggers...")

    # Event loop
    for event in events:
        now_ist       = datetime.now(IST)
        trigger_time  = event['time'] + timedelta(minutes=SCAN_DELAY_MINUTES)
        wait_seconds  = (trigger_time - now_ist).total_seconds()

        if wait_seconds > 0:
            logger.info(
                f"[Bot] Waiting {wait_seconds:.0f}s for: "
                f"{event['title']} at {trigger_time.strftime('%H:%M IST')}"
            )
            time.sleep(wait_seconds)

        # Fire event
        logger.info(f"[Bot] Triggering scan for: {event['title']}")
        send_event_alert(event, datetime.now(IST))

        # Run sentiment pipeline
        try:
            pipeline = SentimentScannerPipeline()
            result   = pipeline.run_pipeline()

            # Generate AI macro summary
            macro_summary = generate_macro_summary(result, event['title'])

            # Send scan complete alert
            send_scan_complete_alert(event, result, macro_summary)

            logger.info(
                f"[Bot] Scan complete: {event['title']} — "
                f"{result.get('processed', 0)} processed, "
                f"{result.get('errors', 0)} errors"
            )

        except Exception as e:
            logger.error(f"[Bot] Pipeline error for {event['title']}: {e}")
            send_error_notification(
                f"Sentiment pipeline failed for event '{event['title']}': {e}",
                "bot"
            )

    logger.info("[Bot] All events processed. Job complete.")


if __name__ == "__main__":
    run_scheduler()
